spring.application.name=RutaDelSabor-Core

# --- CONEXIÓN A POSTGRESQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/rutadelsabor_core_db
spring.datasource.username=postgres
spring.datasource.password=ansu11
spring.datasource.driver-class-name=org.postgresql.Driver

# --- HIBERNATE & JPA ---
# MUY IMPORTANTE: "none" porque ya creamos la BD con scripts SQL.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- SEGURIDAD JWT ---
# Usa una clave secreta muy larga (Base64) de al menos 256 bits.
jwt.secret=Z2FicmllbGRpZWdvamVzdXNqaG9qYW5sZWFuZHJvcmljYXJkbzIyMjIyNzI1MTEwNTA2
# Expiración: 24 horas en milisegundos (86400000)
jwt.expiration=86400000

# --- PUERTO DEL SERVIDOR ---
server.port=8080